plugins:
  - "prettier-plugin-solidity"
printWidth: 120
trailingComma: "all"
semi: true
singleQuote: false
tabWidth: 2
useTabs: false

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: "*.sol"
    options:
      compiler: "0.8.24"
      parser: "solidity-parse"
      tabWidth: 4
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
  - files: "*.tsx"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript", "jsx"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
